name: Push to Replicate

on:
  push:
    branches: [ replicate-cog ]   # run on any commit to this branch
  workflow_dispatch: {}            # optional: manual "Run workflow" button

concurrency:
  group: cog-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Frees ~30GB; handy for big models
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/eliad-openmic/latentsync-cog
